name: Pull Request

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
    branches-ignore:
      - 'main'

jobs:
  pr:
    name: "CI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: [6.7.1, 6.8.2]
        java: [1.8, 11, 15]
    steps:
      - name: Check-out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Set Gradle Version
        run: ./gradlew wrapper --gradle-version ${{ matrix.gradle }}
      - name: Test Plugin Directly with Gradle
        run: ./gradlew check
        working-directory: pixeloutlaw-gradle-plugin
      - name: Test Plugin Application with Gradle
        run: ./gradlew check
