name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ":pencil2: Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ":rocket: Create GitHub release"
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Write Plugin Publishing Values
        run: ../gradlew writePublishPluginSecrets
        env:
          CI: true
        working-directory: pixeloutlaw-gradle-plugin
      - name: Publish Plugins to Gradle Plugin Portal
        run: ../gradlew publishPlugins
        working-directory: pixeloutlaw-gradle-plugin
